apiVersion: v1
kind: Service
metadata:
  name: nodejs-lb-nodeport
spec:
  type: NodePort
  selector:
    app: nodejs-lb
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
