apiVersion: v1
kind: Pod
metadata:
  name: large-pod
  namespace: development
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          cpu: "5"
          memory: 10Gi
        limits:
          cpu: "10"
          memory: 20Gi
