apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
    - name: app
      image: nginx:1.25
      resources:
        requests:
          cpu: "250m" # Guaranteed 0.25 core
        limits:
          cpu: "500m" # Max 0.5 core
