apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-us-east
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      region: us-east
  template:
    metadata:
      labels:
        app: web
        region: us-east
    spec:
      containers:
        - name: web
          image: nginx:1.25
      nodeSelector:
        region: us-east
