apiVersion: v1
kind: Pod
metadata:
  name: mixed-users
spec:
  containers:
    - name: app1
      image: app1:latest
      securityContext:
        runAsUser: 1000
    - name: app2
      image: app2:latest
      securityContext:
        runAsUser: 2000
