apiVersion: v1
kind: Pod
metadata:
  name: supplemental-groups
spec:
  securityContext:
    runAsUser: 1000
    supplementalGroups: [4000, 5000]
  containers:
    - name: app
      image: myapp:latest
