apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod-frontend
  labels:
    app: nginx
    environment: production
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod-backend
  labels:
    app: nginx
    environment: production
    tier: backend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev-frontend
  labels:
    app: nginx
    environment: development
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-prod
  labels:
    app: postgres
    environment: production
    tier: database
spec:
  containers:
    - name: postgres
      image: postgres:15
      ports:
        - containerPort: 5432