apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data
  labels:
    type: local
    env: production
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s/pv-local-data
