apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100
    path: /exports/k8s-data
