apiVersion: v1
kind: Pod
metadata:
  name: maintenance-pod
spec:
  tolerations:
    - key: maintenance
      operator: Equal
      value: "true"
      effect: NoExecute
      tolerationSeconds: 300 # 5 min
  containers:
    - name: app
      image: myapp:latest
