apiVersion: v1
kind: Pod
metadata:
  name: temporary-pod
spec:
  tolerations:
    - key: maintenance
      operator: Equal
      value: "true"
      effect: NoExecute
      tolerationSeconds: 3600 # 1 hour
  containers:
    - name: app
      image: myapp:latest
