apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: default
type: Opaque
data:
  username: YWRtaW4= # base64 from "admin"
  password: c2VjcmV0cGFzcw== # base64 from "secretpass"
